### ISSUE TITLE
Similar project but for sponsors

### ISSUE THREAD

**Issue by camjac251** [Pentalex/twitchtos#10]
I was browsing through and found your repository and it makes me happy that someone is making something for streamers to avoid ToS videos.

Have you seen SponsorBlock for browsers? https://sponsor.ajay.app

I was wondering if someone could take this codebase and make it work for streamer TOS. It supports tagging certain time frames, setting their sponsor type (self,ad,intro) and submitting them to a DB (and a voting system to weed out the incorrect ones).
It only has skipping supported right now but it would be cool (if it was possible to cater it for twitch) to support blanking a video segment or muting an audio segment so a video could still be watched without it being skipped all together.

The dev is pretty active on Discord so I'm curious if maybe he even would be interested.

**Comment by pentalex** [comment]
Hey. First of all: I'm glad this project is getting recognized! 
Unfortunately I'm just a 16 year old kid that made this thing within 2 weeks for my streamer friends. I don't have the expertise yet to make something like that by myself, let alone try to work off someone else's codebase. Maybe with a smaller project, but this seems like a huge learning curve and a lot of work and it would take me a lot of time to do this.  The level is just too high.

I don't have the time or skills to do something like this for free, I'm sorry.
Hope you have a nice day!

**Comment by pentalex** [comment]
Reopened if you have any questions/concerns.

**Comment by pentalex** [comment]
Closed due to inactivity.
