### ISSUE TITLE
No sign in option for Firefox

### ISSUE THREAD

**Issue by j9mg** [Pentalex/twitchtos#12]
![sign](https://user-images.githubusercontent.com/74982339/101403983-f5247800-3910-11eb-84aa-0f891b4851c4.png)

There seems to be no option for me to sign in to Twitch when clicking on the extension. 
Running on latest Firefox 83.0 (64-bit).

**Comment by pentalex** [comment]
Hey there! I apologize for the issues you are facing. Are you running the build on GitHub or the build on the Firefox Add-on store?

**Comment by j9mg** [comment]
I'm running it on Firefox add-on store.

**Comment by pentalex** [comment]
Have you tried reinstalling the extension?

**Comment by j9mg** [comment]
> Have you tried reinstalling the extension?

Yes i did. For some reason after restarting firefox numerous times, it's fixed and the sign in option is back and im able to sign in.

**Comment by pentalex** [comment]
Awesome, please let me know if you have any more issues.
Closing for now
